name: baby_monitor

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    # FIX: macでは/dev/video0がないため、エラーになる
    ports:
      - "8000:5000"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - .:/app
